spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:paas_db}?sslmode=disable&amp;currentSchema=${DB_SCHEMA:paas}&amp;useSSL=true
    username: ${DB_USER:paas_user}
    password: ${DB_PASSWORD:paas_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
